spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: picket
    password: picket

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      hibernate:
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 797661503883-i0c3508b56cchat7selr369l9q85dfgf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  config:
    activate:
      on-profile: jwt

  mail:
    host: smtp.gmail.com
    port: 587
    username: "jiwoong423"
    password: "bvehowlutsppsdsi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: Info
    com.swyg.picketbackend : debug
    org.springframework.security: debug


springdoc:
  show-login-endpoint: true

server:
  forward-headers-strategy: framework

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

cloud:
  aws:
    s3:
      bucket: swyg-picket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA3RTEIKP5KM3EBN42
      secretKey: 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

